all: cat pwd tofile wc lsf gtushell bunedu
cat: cat.c
	gcc -o cat cat.c
pwd: pwd.c
	gcc -o pwd pwd.c
tofile: tofile.c
	gcc -o tofile tofile.c
wc: wc.c
	gcc -o wc wc.c
lsf: lsf.c
	gcc -o lsf lsf.c
gtushell: gtushell.c
	gcc -o gtushell gtushell.c
bunedu: bunedu.c
	gcc -o bunedu bunedu.c

